# Generated by Django 4.2.5 on 2023-10-04 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Customers',
        ),
    ]
