# Generated by Django 4.2.5 on 2023-10-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_alter_customers_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='success',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
