# Generated by Django 4.2.5 on 2023-10-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_customers_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='success',
            field=models.BooleanField(null=True),
        ),
    ]
