# Generated by Django 4.2.5 on 2023-10-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_alter_customers_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='plan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
